name: qrcode_hd
version: 1.0.2+1
publish_to: none
description: Applicatyion de génération de QR Code
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  qr_flutter: ^4.1.0
  url_launcher: ^6.1.12
  path_provider: ^2.0.15
  gallery_saver: ^2.3.2
  string_validator: ^1.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_json_viewer: ^1.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img/

